### ISSUE TITLE
Error when running brew install qtautoupdater 

### ISSUE THREAD

**Issue by AmyXS** [Skycoder42/homebrew-qt-modules#2]
Hi there, I got the following error when installing the package qtautoupdater. Please help! :)

Qt 5.14.0, macOS Mojave 10.14.6

Here's the output from make
[02.make.txt](https://github.com/Skycoder42/homebrew-qt-modules/files/4088998/02.make.txt)

**Comment by Skycoder42** [comment]
It should work now. See https://github.com/Skycoder42/homebrew-qt-modules/actions/runs/33294316
